update fw.dq_testcases
set testcase_sql = 
	'SELECT 
	id_customer, 
	cust_num, 
	data_src, 
	is_current, 
	terr_div, 
	terr_div_name, 
	div_code, 
	cust_name, 
	stat_cust_num, 
	id_cust_contact, 
	inn, 
	stat, 
	stat_name, 
	address, 
	city, 
	ma_code, 
	ma_name, 
	ma_chief, 
	ma_chief_name, 
	to_char(date_created, ''yyyy-mm-dd'') as date_created, 
	coalesce (to_char(time_created, ''HH24:MI''),''N/A'') as time_created, 
	slmn_num, 
	slmn_name, 
	"operator", 
	--to_char(date_mod, ''yyyy-mm-dd'') as date_mod, 
	user_mod, 
	to_char(date_first, ''yyyy-mm-dd'') as date_first, 
	to_char(date_last, ''yyyy-mm-dd'') as date_last, 
	cust_price_type, 
	cust_price_type_name, 
	standard_order, 
	sort_name, 
	ppd_coll, 
	tax_region, 
	terr_code, 
	credit_limit, 
	credit_days, 
	charge_to, 
	price_level, 
	open_order, 
	last_amt_pay, 
	to_char(last_date_pay, ''yyyy-mm-dd'') as last_date_pay, 
	last_inv_amt, 
	to_char(inv_date_last, ''yyyy-mm-dd'') as inv_date_last, 
	tax_method, 
	cust_type, 
	relation, 
	corp, 
	id_last_visit, 
	cust_juri_type, 
	rival_id, 
	serv_code, 
	wsd_code, 
	opf_code, 
	super_market, 
	z_ma_code, 
	cour_sal_inc, 
	tax_status, 
	on_control, 
	to_char(date_on_control, ''yyyy-mm-dd'') as date_on_control, 
	user_on_control, 
	ch_ord_lim, 
	term_code, 
	is_def_cust, 
	first_bonus, 
	to_char(b_date, ''yyyy-mm-dd'') as b_date, 
	to_char(e_date, ''yyyy-mm-dd'') as e_date, 
	parent_div, 
	serv_instr_code, 
	is_cert_exists, 
	sum_cert, 
	to_char(b_date_cert, ''yyyy-mm-dd'') as b_date_cert, 
	to_char(e_date_cert, ''yyyy-mm-dd'') as e_date_cert, 
	id_div, 
	id_ma_hist, 
	is_any_mrk, 
	last_mrk_code, 
	to_char(last_mrk_b_date, ''yyyy-mm-dd'') as last_mrk_b_date, 
	to_char(last_mrk_e_date, ''yyyy-mm-dd'') as last_mrk_e_date, 
	is_mrk, 
	demand_num, 
	bus_reg_code, 
	to_char(first_pay_date, ''yyyy-mm-dd'') as first_pay_date, 
	def_disc_pct, 
	"segment", 
	is_correct_sale_div, 
	p_segment, 
	fin_code, 
	"blocked", 
	cur_terr_div, 
	cur_div_code, 
	tar_code, 
	stat_cust_name, 
	to_char(stat_first_pay_date, ''yyyy-mm-dd'') as stat_first_pay_date, 
	network_id, 
	network_name, 
	stp_ma_code, 
	stp_ma_name, 
	ma_type_id, 
	ma_type_name, 
	l_60_operations, 
	flag_in_action, 
	terr_ma_code, 
	terr_ma_name, 
	tar_seg_id, 
	full_code, 
	desc_seg, 
	top_tar_seg_id, 
	top_full_code, 
	top_desc_seg, 
	to_char(first_pbv_date, ''yyyy-mm-dd'') as first_pbv_date, 
	to_char(last_pbv_date, ''yyyy-mm-dd'') as last_pbv_date, 
	to_char(date_lose, ''yyyy-mm-dd'') as date_lose, 
	to_char(date_of_delete, ''yyyy-mm-dd'') as date_of_delete, 
	lose_after, 
	free_deliv, 
	reason_of_del_desc, 
	sub_kladr_code, 
	dist_client, 
	rate_code, 
	rfm_marker, 
	sap_cust_id,
	glavkod_flag, 
	to_char(first_date_pay_glav, ''yyyy-mm-dd'') as first_date_pay_glav, 
	to_char(last_date_pay_glav, ''yyyy-mm-dd'') as last_date_pay_glav, 
	stat_glav, 
	to_char(date_lose_glav, ''yyyy-mm-dd'') as date_lose_glav, 
	sum_after_due_date, 
	credit_limit_add_sum, 
	block_order_inn, 
	block_shipping_inn, 
	ship_doc_type, 
	round_nds, 
	price_region, 
	export_sales, 
	sap_participation_type, 
	flag_guid, 
	ogrn, 
	edo_tender,
	ecqu
	FROM kdw.customer_cd
	where e_date = to_date(''2022-09-30'', ''yyyy-mm-dd'')',
benchmark_sql = 
	'SELECT 
	id_customer, 
	cust_num, 
	data_src, 
	cd.is_current, 
	terr_div, 
	terr_div_name, 
	div_code, 
	cust_name, 
	stat_cust_num, 
	id_cust_contact, 
	inn, 
	stat, 
	stat_name, 
	address, 
	city, 
	ma_code, 
	ma_name, 
	ma_chief, 
	ma_chief_name, 
	to_char(d.CAL_DATE, ''yyyy-mm-dd'') AS date_created,
	t.time_name as time_creatded, 
	slmn_num, 
	slmn_name, 
	operator, 
	--to_char(dm.CAL_DATE, ''yyyy-mm-dd'') as date_mod, 
	user_mod, 
	to_char(df.CAL_DATE , ''yyyy-mm-dd'') as date_first, 
	to_char(dl.CAL_DATE , ''yyyy-mm-dd'') as date_last, 
	cust_price_type, 
	cust_price_type_name, 
	standard_order, 
	sort_name, 
	ppd_coll, 
	tax_region, 
	terr_code, 
	credit_limit, 
	credit_days, 
	charge_to, 
	price_level, 
	open_order, 
	last_amt_pay, 
	to_char(ld.CAL_DATE , ''yyyy-mm-dd'') as last_date_pay, 
	last_inv_amt, 
	to_char(id.CAL_DATE , ''yyyy-mm-dd'') as inv_date_last, 
	tax_method, 
	cust_type, 
	relation, 
	corp, 
	id_last_visit, 
	cust_juri_type, 
	rival_id, 
	serv_code, 
	wsd_code, 
	opf_code, 
	super_market, 
	z_ma_code, 
	cour_sal_inc, 
	tax_status, 
	on_control, 
	to_char(date_on_control, ''yyyy-mm-dd'') as date_on_control, 
	user_on_control, 
	ch_ord_lim, 
	term_code, 
	is_def_cust, 
	first_bonus, 
	to_char(b_date, ''yyyy-mm-dd'') as b_date, 
	to_char(e_date, ''yyyy-mm-dd'') as e_date, 
	parent_div, 
	serv_instr_code, 
	is_cert_exists, 
	sum_cert, 
	to_char(b_date_cert, ''yyyy-mm-dd'') as b_date_cert, 
	to_char(e_date_cert, ''yyyy-mm-dd'') as e_date_cert, 
	id_div, 
	id_ma_hist, 
	is_any_mrk, 
	last_mrk_code, 
	to_char(last_mrk_b_date, ''yyyy-mm-dd'') as last_mrk_b_date, 
	to_char(last_mrk_e_date, ''yyyy-mm-dd'') as last_mrk_e_date, 
	is_mrk, 
	demand_num, 
	bus_reg_code, 
	to_char(first_pay_date, ''yyyy-mm-dd'') as first_pay_date, 
	def_disc_pct, 
	segment, 
	is_correct_sale_div, 
	p_segment, 
	fin_code, 
	blocked, 
	cur_terr_div, 
	cur_div_code, 
	tar_code, 
	stat_cust_name, 
	to_char(stat_first_pay_date, ''yyyy-mm-dd'') as stat_first_pay_date, 
	network_id, 
	network_name, 
	stp_ma_code, 
	stp_ma_name, 
	ma_type_id, 
	ma_type_name, 
	l_60_operations, 
	flag_in_action, 
	terr_ma_code, 
	terr_ma_name, 
	tar_seg_id, 
	full_code, 
	desc_seg, 
	top_tar_seg_id, 
	top_full_code, 
	top_desc_seg, 
	to_char(first_pbv_date, ''yyyy-mm-dd'') as first_pbv_date, 
	to_char(last_pbv_date, ''yyyy-mm-dd'') as last_pbv_date, 
	to_char(date_lose, ''yyyy-mm-dd'') as date_lose, 
	to_char(date_of_delete, ''yyyy-mm-dd'') as date_of_delete, 
	lose_after, 
	free_deliv, 
	reason_of_del_desc, 
	sub_kladr_code, 
	dist_client, 
	rate_code, 
	rfm_marker, 
	sap_cust_id,
	glavkod_flag, 
	to_char(first_date_pay_glav, ''yyyy-mm-dd'') as first_date_pay_glav, 
	to_char(last_date_pay_glav, ''yyyy-mm-dd'') as last_date_pay_glav, 
	stat_glav, 
	to_char(date_lose_glav, ''yyyy-mm-dd'') as date_lose_glav, 
	sum_after_due_date, 
	credit_limit_add_sum, 
	block_order_inn, 
	block_shipping_inn, 
	ship_doc_type, 
	round_nds, 
	price_region, 
	export_sales, 
	sap_participation_type, 
	flag_guid, 
	ogrn, 
	edo_tender,
	ecqu  
	FROM kdw.CUSTOMER_CD cd 
	  left outer join kdw.calendar_d d 
	    on d.id_date = cd.id_date_created 
	  left outer join kdw.time_d t  
	    on t.id_time = cd.id_time_created 
	  left outer join kdw.calendar_d dm 
	    on dm.id_date = cd.id_date_mod 
	  left outer join kdw.calendar_d df 
	    on df.id_date = cd.id_date_first 
	  left outer join kdw.calendar_d dl 
	    on dl.id_date = cd.id_date_last 
	  left outer join kdw.calendar_d ld 
	    on ld.id_date = cd.id_last_date_pay 
	  left outer join kdw.calendar_d id 
	    on id.id_date = cd.id_inv_date_last
	where cd.e_date = to_date(''2022-09-30'', ''yyyy-mm-dd'')'
where object_name like 'kdw.customer_cd'
 and testcase_id = '10';


update fw.dq_testcases
set testcase_sql = 
	'SELECT 
	id_customer, 
	cust_num, 
	data_src, 
	is_current, 
	terr_div, 
	terr_div_name, 
	div_code, 
	cust_name, 
	stat_cust_num, 
	id_cust_contact, 
	inn, 
	stat, 
	stat_name, 
	address, 
	city, 
	ma_code, 
	ma_name, 
	ma_chief, 
	ma_chief_name, 
	to_char(date_created, ''yyyy-mm-dd'') as date_created, 
	coalesce (to_char(time_created, ''HH24:MI''),''N/A'') as time_created, 
	slmn_num, 
	slmn_name, 
	"operator", 
	--to_char(date_mod, ''yyyy-mm-dd'') as date_mod, 
	user_mod, 
	to_char(date_first, ''yyyy-mm-dd'') as date_first, 
	to_char(date_last, ''yyyy-mm-dd'') as date_last, 
	cust_price_type, 
	cust_price_type_name, 
	standard_order, 
	sort_name, 
	ppd_coll, 
	tax_region, 
	terr_code, 
	credit_limit, 
	credit_days, 
	charge_to, 
	price_level, 
	open_order, 
	last_amt_pay, 
	to_char(last_date_pay, ''yyyy-mm-dd'') as last_date_pay, 
	last_inv_amt, 
	to_char(inv_date_last, ''yyyy-mm-dd'') as inv_date_last, 
	tax_method, 
	cust_type, 
	relation, 
	corp, 
	id_last_visit, 
	cust_juri_type, 
	rival_id, 
	serv_code, 
	wsd_code, 
	opf_code, 
	super_market, 
	z_ma_code, 
	cour_sal_inc, 
	tax_status, 
	on_control, 
	to_char(date_on_control, ''yyyy-mm-dd'') as date_on_control, 
	user_on_control, 
	ch_ord_lim, 
	term_code, 
	is_def_cust, 
	first_bonus, 
	to_char(b_date, ''yyyy-mm-dd'') as b_date, 
	to_char(e_date, ''yyyy-mm-dd'') as e_date, 
	parent_div, 
	serv_instr_code, 
	is_cert_exists, 
	sum_cert, 
	to_char(b_date_cert, ''yyyy-mm-dd'') as b_date_cert, 
	to_char(e_date_cert, ''yyyy-mm-dd'') as e_date_cert, 
	id_div, 
	id_ma_hist, 
	is_any_mrk, 
	last_mrk_code, 
	to_char(last_mrk_b_date, ''yyyy-mm-dd'') as last_mrk_b_date, 
	to_char(last_mrk_e_date, ''yyyy-mm-dd'') as last_mrk_e_date, 
	is_mrk, 
	demand_num, 
	bus_reg_code, 
	to_char(first_pay_date, ''yyyy-mm-dd'') as first_pay_date, 
	def_disc_pct, 
	"segment", 
	is_correct_sale_div, 
	p_segment, 
	fin_code, 
	"blocked", 
	cur_terr_div, 
	cur_div_code, 
	tar_code, 
	stat_cust_name, 
	to_char(stat_first_pay_date, ''yyyy-mm-dd'') as stat_first_pay_date, 
	network_id, 
	network_name, 
	stp_ma_code, 
	stp_ma_name, 
	ma_type_id, 
	ma_type_name, 
	l_60_operations, 
	flag_in_action, 
	terr_ma_code, 
	terr_ma_name, 
	tar_seg_id, 
	full_code, 
	desc_seg, 
	top_tar_seg_id, 
	top_full_code, 
	top_desc_seg, 
	to_char(first_pbv_date, ''yyyy-mm-dd'') as first_pbv_date, 
	to_char(last_pbv_date, ''yyyy-mm-dd'') as last_pbv_date, 
	to_char(date_lose, ''yyyy-mm-dd'') as date_lose, 
	to_char(date_of_delete, ''yyyy-mm-dd'') as date_of_delete, 
	lose_after, 
	free_deliv, 
	reason_of_del_desc, 
	sub_kladr_code, 
	dist_client, 
	rate_code, 
	rfm_marker, 
	sap_cust_id,
	glavkod_flag, 
	to_char(first_date_pay_glav, ''yyyy-mm-dd'') as first_date_pay_glav, 
	to_char(last_date_pay_glav, ''yyyy-mm-dd'') as last_date_pay_glav, 
	stat_glav, 
	to_char(date_lose_glav, ''yyyy-mm-dd'') as date_lose_glav, 
	sum_after_due_date, 
	credit_limit_add_sum, 
	block_order_inn, 
	block_shipping_inn, 
	ship_doc_type, 
	round_nds, 
	price_region, 
	export_sales, 
	sap_participation_type, 
	flag_guid, 
	ogrn, 
	edo_tender,
	ecqu 
	FROM kdw.customer_cd
	where id_customer = 40769447',
benchmark_sql = 
	'SELECT 
	id_customer, 
	cust_num, 
	data_src, 
	cd.is_current, 
	terr_div, 
	terr_div_name, 
	div_code, 
	cust_name, 
	stat_cust_num, 
	id_cust_contact, 
	inn, 
	stat, 
	stat_name, 
	address, 
	city, 
	ma_code, 
	ma_name, 
	ma_chief, 
	ma_chief_name, 
	to_char(d.CAL_DATE, ''yyyy-mm-dd'') AS date_created,
	t.time_name as time_creatded, 
	slmn_num, 
	slmn_name, 
	operator, 
	--to_char(dm.CAL_DATE, ''yyyy-mm-dd'') as date_mod, 
	user_mod, 
	to_char(df.CAL_DATE , ''yyyy-mm-dd'') as date_first, 
	to_char(dl.CAL_DATE , ''yyyy-mm-dd'') as date_last, 
	cust_price_type, 
	cust_price_type_name, 
	standard_order, 
	sort_name, 
	ppd_coll, 
	tax_region, 
	terr_code, 
	credit_limit, 
	credit_days, 
	charge_to, 
	price_level, 
	open_order, 
	last_amt_pay, 
	to_char(ld.CAL_DATE , ''yyyy-mm-dd'') as last_date_pay, 
	last_inv_amt, 
	to_char(id.CAL_DATE , ''yyyy-mm-dd'') as inv_date_last, 
	tax_method, 
	cust_type, 
	relation, 
	corp, 
	id_last_visit, 
	cust_juri_type, 
	rival_id, 
	serv_code, 
	wsd_code, 
	opf_code, 
	super_market, 
	z_ma_code, 
	cour_sal_inc, 
	tax_status, 
	on_control, 
	to_char(date_on_control, ''yyyy-mm-dd'') as date_on_control, 
	user_on_control, 
	ch_ord_lim, 
	term_code, 
	is_def_cust, 
	first_bonus, 
	to_char(b_date, ''yyyy-mm-dd'') as b_date, 
	to_char(e_date, ''yyyy-mm-dd'') as e_date, 
	parent_div, 
	serv_instr_code, 
	is_cert_exists, 
	sum_cert, 
	to_char(b_date_cert, ''yyyy-mm-dd'') as b_date_cert, 
	to_char(e_date_cert, ''yyyy-mm-dd'') as e_date_cert, 
	id_div, 
	id_ma_hist, 
	is_any_mrk, 
	last_mrk_code, 
	to_char(last_mrk_b_date, ''yyyy-mm-dd'') as last_mrk_b_date, 
	to_char(last_mrk_e_date, ''yyyy-mm-dd'') as last_mrk_e_date, 
	is_mrk, 
	demand_num, 
	bus_reg_code, 
	to_char(first_pay_date, ''yyyy-mm-dd'') as first_pay_date, 
	def_disc_pct, 
	segment, 
	is_correct_sale_div, 
	p_segment, 
	fin_code, 
	blocked, 
	cur_terr_div, 
	cur_div_code, 
	tar_code, 
	stat_cust_name, 
	to_char(stat_first_pay_date, ''yyyy-mm-dd'') as stat_first_pay_date, 
	network_id, 
	network_name, 
	stp_ma_code, 
	stp_ma_name, 
	ma_type_id, 
	ma_type_name, 
	l_60_operations, 
	flag_in_action, 
	terr_ma_code, 
	terr_ma_name, 
	tar_seg_id, 
	full_code, 
	desc_seg, 
	top_tar_seg_id, 
	top_full_code, 
	top_desc_seg, 
	to_char(first_pbv_date, ''yyyy-mm-dd'') as first_pbv_date, 
	to_char(last_pbv_date, ''yyyy-mm-dd'') as last_pbv_date, 
	to_char(date_lose, ''yyyy-mm-dd'') as date_lose, 
	to_char(date_of_delete, ''yyyy-mm-dd'') as date_of_delete, 
	lose_after, 
	free_deliv, 
	reason_of_del_desc, 
	sub_kladr_code, 
	dist_client, 
	rate_code, 
	rfm_marker, 
	sap_cust_id,
	glavkod_flag, 
	to_char(first_date_pay_glav, ''yyyy-mm-dd'') as first_date_pay_glav, 
	to_char(last_date_pay_glav, ''yyyy-mm-dd'') as last_date_pay_glav, 
	stat_glav, 
	to_char(date_lose_glav, ''yyyy-mm-dd'') as date_lose_glav, 
	sum_after_due_date, 
	credit_limit_add_sum, 
	block_order_inn, 
	block_shipping_inn, 
	ship_doc_type, 
	round_nds, 
	price_region, 
	export_sales, 
	sap_participation_type, 
	flag_guid, 
	ogrn, 
	edo_tender,
	ecqu 
	FROM kdw.CUSTOMER_CD cd 
	  left outer join kdw.calendar_d d 
	    on d.id_date = cd.id_date_created 
	  left outer join kdw.time_d t  
	    on t.id_time = cd.id_time_created 
	  left outer join kdw.calendar_d dm 
	    on dm.id_date = cd.id_date_mod 
	  left outer join kdw.calendar_d df 
	    on df.id_date = cd.id_date_first 
	  left outer join kdw.calendar_d dl 
	    on dl.id_date = cd.id_date_last 
	  left outer join kdw.calendar_d ld 
	    on ld.id_date = cd.id_last_date_pay 
	  left outer join kdw.calendar_d id 
	    on id.id_date = cd.id_inv_date_last
	where cd.id_customer = 40769447'
where object_name like 'kdw.customer_cd'
 and testcase_id = '11';

update fw.dq_testcases
set testcase_sql = 
	'SELECT 
	id_customer, 
	cust_num, 
	data_src, 
	is_current, 
	terr_div, 
	terr_div_name, 
	div_code, 
	cust_name, 
	stat_cust_num, 
	id_cust_contact, 
	inn, 
	stat, 
	stat_name, 
	address, 
	city, 
	ma_code, 
	ma_name, 
	ma_chief, 
	ma_chief_name, 
	to_char(date_created, ''yyyy-mm-dd'') as date_created, 
	coalesce (to_char(time_created, ''HH24:MI''),''N/A'') as time_created, 
	slmn_num, 
	slmn_name, 
	"operator", 
	--to_char(date_mod, ''yyyy-mm-dd'') as date_mod, 
	user_mod, 
	to_char(date_first, ''yyyy-mm-dd'') as date_first, 
	to_char(date_last, ''yyyy-mm-dd'') as date_last, 
	cust_price_type, 
	cust_price_type_name, 
	standard_order, 
	sort_name, 
	ppd_coll, 
	tax_region, 
	terr_code, 
	credit_limit, 
	credit_days, 
	charge_to, 
	price_level, 
	open_order, 
	last_amt_pay, 
	to_char(last_date_pay, ''yyyy-mm-dd'') as last_date_pay, 
	last_inv_amt, 
	to_char(inv_date_last, ''yyyy-mm-dd'') as inv_date_last, 
	tax_method, 
	cust_type, 
	relation, 
	corp, 
	id_last_visit, 
	cust_juri_type, 
	rival_id, 
	serv_code, 
	wsd_code, 
	opf_code, 
	super_market, 
	z_ma_code, 
	cour_sal_inc, 
	tax_status, 
	on_control, 
	to_char(date_on_control, ''yyyy-mm-dd'') as date_on_control, 
	user_on_control, 
	ch_ord_lim, 
	term_code, 
	is_def_cust, 
	first_bonus, 
	to_char(b_date, ''yyyy-mm-dd'') as b_date, 
	to_char(e_date, ''yyyy-mm-dd'') as e_date, 
	parent_div, 
	serv_instr_code, 
	is_cert_exists, 
	sum_cert, 
	to_char(b_date_cert, ''yyyy-mm-dd'') as b_date_cert, 
	to_char(e_date_cert, ''yyyy-mm-dd'') as e_date_cert, 
	id_div, 
	id_ma_hist, 
	is_any_mrk, 
	last_mrk_code, 
	to_char(last_mrk_b_date, ''yyyy-mm-dd'') as last_mrk_b_date, 
	to_char(last_mrk_e_date, ''yyyy-mm-dd'') as last_mrk_e_date, 
	is_mrk, 
	demand_num, 
	bus_reg_code, 
	to_char(first_pay_date, ''yyyy-mm-dd'') as first_pay_date, 
	def_disc_pct, 
	"segment", 
	is_correct_sale_div, 
	p_segment, 
	fin_code, 
	"blocked", 
	cur_terr_div, 
	cur_div_code, 
	tar_code, 
	stat_cust_name, 
	to_char(stat_first_pay_date, ''yyyy-mm-dd'') as stat_first_pay_date, 
	network_id, 
	network_name, 
	stp_ma_code, 
	stp_ma_name, 
	ma_type_id, 
	ma_type_name, 
	l_60_operations, 
	flag_in_action, 
	terr_ma_code, 
	terr_ma_name, 
	tar_seg_id, 
	full_code, 
	desc_seg, 
	top_tar_seg_id, 
	top_full_code, 
	top_desc_seg, 
	to_char(first_pbv_date, ''yyyy-mm-dd'') as first_pbv_date, 
	to_char(last_pbv_date, ''yyyy-mm-dd'') as last_pbv_date, 
	to_char(date_lose, ''yyyy-mm-dd'') as date_lose, 
	to_char(date_of_delete, ''yyyy-mm-dd'') as date_of_delete, 
	lose_after, 
	free_deliv, 
	reason_of_del_desc, 
	sub_kladr_code, 
	dist_client, 
	rate_code, 
	rfm_marker, 
	sap_cust_id,
	glavkod_flag, 
	to_char(first_date_pay_glav, ''yyyy-mm-dd'') as first_date_pay_glav, 
	to_char(last_date_pay_glav, ''yyyy-mm-dd'') as last_date_pay_glav, 
	stat_glav, 
	to_char(date_lose_glav, ''yyyy-mm-dd'') as date_lose_glav, 
	sum_after_due_date, 
	credit_limit_add_sum, 
	block_order_inn, 
	block_shipping_inn, 
	ship_doc_type, 
	round_nds, 
	price_region, 
	export_sales, 
	sap_participation_type, 
	flag_guid, 
	ogrn, 
	edo_tender,
	ecqu 
	FROM kdw.customer_cd
	where e_date = to_date(''2022-12-31'', ''yyyy-mm-dd'')',
benchmark_sql = 
	'SELECT 
	id_customer, 
	cust_num, 
	data_src, 
	cd.is_current, 
	terr_div, 
	terr_div_name, 
	div_code, 
	cust_name, 
	stat_cust_num, 
	id_cust_contact, 
	inn, 
	stat, 
	stat_name, 
	address, 
	city, 
	ma_code, 
	ma_name, 
	ma_chief, 
	ma_chief_name, 
	to_char(d.CAL_DATE, ''yyyy-mm-dd'') AS date_created,
	t.time_name as time_creatded, 
	slmn_num, 
	slmn_name, 
	operator, 
	--to_char(dm.CAL_DATE, ''yyyy-mm-dd'') as date_mod, 
	user_mod, 
	to_char(df.CAL_DATE , ''yyyy-mm-dd'') as date_first, 
	to_char(dl.CAL_DATE , ''yyyy-mm-dd'') as date_last, 
	cust_price_type, 
	cust_price_type_name, 
	standard_order, 
	sort_name, 
	ppd_coll, 
	tax_region, 
	terr_code, 
	credit_limit, 
	credit_days, 
	charge_to, 
	price_level, 
	open_order, 
	last_amt_pay, 
	to_char(ld.CAL_DATE , ''yyyy-mm-dd'') as last_date_pay, 
	last_inv_amt, 
	to_char(id.CAL_DATE , ''yyyy-mm-dd'') as inv_date_last, 
	tax_method, 
	cust_type, 
	relation, 
	corp, 
	id_last_visit, 
	cust_juri_type, 
	rival_id, 
	serv_code, 
	wsd_code, 
	opf_code, 
	super_market, 
	z_ma_code, 
	cour_sal_inc, 
	tax_status, 
	on_control, 
	to_char(date_on_control, ''yyyy-mm-dd'') as date_on_control, 
	user_on_control, 
	ch_ord_lim, 
	term_code, 
	is_def_cust, 
	first_bonus, 
	to_char(b_date, ''yyyy-mm-dd'') as b_date, 
	to_char(e_date, ''yyyy-mm-dd'') as e_date, 
	parent_div, 
	serv_instr_code, 
	is_cert_exists, 
	sum_cert, 
	to_char(b_date_cert, ''yyyy-mm-dd'') as b_date_cert, 
	to_char(e_date_cert, ''yyyy-mm-dd'') as e_date_cert, 
	id_div, 
	id_ma_hist, 
	is_any_mrk, 
	last_mrk_code, 
	to_char(last_mrk_b_date, ''yyyy-mm-dd'') as last_mrk_b_date, 
	to_char(last_mrk_e_date, ''yyyy-mm-dd'') as last_mrk_e_date, 
	is_mrk, 
	demand_num, 
	bus_reg_code, 
	to_char(first_pay_date, ''yyyy-mm-dd'') as first_pay_date, 
	def_disc_pct, 
	segment, 
	is_correct_sale_div, 
	p_segment, 
	fin_code, 
	blocked, 
	cur_terr_div, 
	cur_div_code, 
	tar_code, 
	stat_cust_name, 
	to_char(stat_first_pay_date, ''yyyy-mm-dd'') as stat_first_pay_date, 
	network_id, 
	network_name, 
	stp_ma_code, 
	stp_ma_name, 
	ma_type_id, 
	ma_type_name, 
	l_60_operations, 
	flag_in_action, 
	terr_ma_code, 
	terr_ma_name, 
	tar_seg_id, 
	full_code, 
	desc_seg, 
	top_tar_seg_id, 
	top_full_code, 
	top_desc_seg, 
	to_char(first_pbv_date, ''yyyy-mm-dd'') as first_pbv_date, 
	to_char(last_pbv_date, ''yyyy-mm-dd'') as last_pbv_date, 
	to_char(date_lose, ''yyyy-mm-dd'') as date_lose, 
	to_char(date_of_delete, ''yyyy-mm-dd'') as date_of_delete, 
	lose_after, 
	free_deliv, 
	reason_of_del_desc, 
	sub_kladr_code, 
	dist_client, 
	rate_code, 
	rfm_marker, 
	sap_cust_id,
	glavkod_flag, 
	to_char(first_date_pay_glav, ''yyyy-mm-dd'') as first_date_pay_glav, 
	to_char(last_date_pay_glav, ''yyyy-mm-dd'') as last_date_pay_glav, 
	stat_glav, 
	to_char(date_lose_glav, ''yyyy-mm-dd'') as date_lose_glav, 
	sum_after_due_date, 
	credit_limit_add_sum, 
	block_order_inn, 
	block_shipping_inn, 
	ship_doc_type, 
	round_nds, 
	price_region, 
	export_sales, 
	sap_participation_type, 
	flag_guid, 
	ogrn, 
	edo_tender,
	ecqu 
	FROM kdw.CUSTOMER_CD cd 
	  left outer join kdw.calendar_d d 
	    on d.id_date = cd.id_date_created 
	  left outer join kdw.time_d t  
	    on t.id_time = cd.id_time_created 
	  left outer join kdw.calendar_d dm 
	    on dm.id_date = cd.id_date_mod 
	  left outer join kdw.calendar_d df 
	    on df.id_date = cd.id_date_first 
	  left outer join kdw.calendar_d dl 
	    on dl.id_date = cd.id_date_last 
	  left outer join kdw.calendar_d ld 
	    on ld.id_date = cd.id_last_date_pay 
	  left outer join kdw.calendar_d id 
	    on id.id_date = cd.id_inv_date_last where cd.e_date = to_date(''2022-12-31'', ''yyyy-mm-dd'')'
where object_name like 'kdw.customer_cd'
 and testcase_id = '39';
